import React, { useState, useEffect } from 'react';
import api from '../../services/api';

function ReportList() {
  const [reports, setReports] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const response = await api.get('/reports');
        setReports(response.data.reports);
      } catch (err) {
        setError(err.response?.data?.message || 'Failed to fetch reports');
      }
    };
    fetchReports();
  }, []);

  return (
    <div className="report-list">
      <h2>Reports</h2>
      {error && <p className="error">{error}</p>}
      <ul>
        {reports.map((report) => (
          <li key={report.ReportID}>
            {report.ReportType} - Generated by {report.AdminName} on 
            {new Date(report.GeneratedDate).toLocaleDateString()}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default ReportList;